#/usr/bin/sh

# create units directory in fpcsrc
mkdir ../units
mkdir ../units/arm-embedded

# save original sysutils.inc
cp ../objpas/sysutils/sysutils.inc ../objpas/sysutils/oldsysutils.inc 

# patch sysutils.inc for embedded ARMV6M
patch ../objpas/sysutils/sysutils.inc < embedded_sysutils.patch

# compile RTL for arm embedded systems
echo Compile RTL for arm-embedded

$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- @system.cfg -Us -Sg system.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  -Fi../objpas ../objpas/objpas.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../objpas/sysconst.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  heapmgr.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -Fi../objpas/sysutils sysutils.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../objpas/math.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/sortbase.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../objpas/rtlconsts.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -Sg  ../objpas/typinfo.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../objpas/types.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../objpas/fgl.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -Fi../objpas/classes  classes.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/macpas.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/getopts.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/strings.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/exeinfo.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/lineinfo.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -Sg  ../inc/softfpu.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -g arm/lpc8xx.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -g arm/lpc11xx.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -g arm/lpc122x.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -g arm/stm32f0xx.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -g arm/nrf51.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -g arm/cortexm0.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi- -g arm/rp2040.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/uuchar.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/iso7185.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  dos.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/extpas.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  consoleio.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/ctypes.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  ../inc/charset.pp
$1/fpcupdeluxe/fpc/bin/x86_64-linux/ppcrossarm -Cparmv6m -Ur -Tembedded -Parm -XParm-none-eabi- -Ur -Xs -O2 -n -Fi../inc -Fi../arm -FD$1/fpcupdeluxe/cross/bin/arm-embedded -FE. -FU$1/fpcupdeluxe/fpcsrc/rtl/units/arm-embedded -vw-n-h-l-d-u-t-p-c- -dFPC_ARMHF -darm -dRELEASE -CaEABI -FD$1/fpcupdeluxe/cross/bin/arm-embedded -XParm-none-eabi-  -Fu../inc -Fi../charmaps ../charmaps/cpall.pas

# copy ppu files to fpc unit
echo Move ppu files to fpc/units
mv $1fpcupdeluxe/fpcsrc/rtl/units/arm-embedded/*.* $1/fpcupdeluxe/fpc/units/arm-embedded/armv6m/eabi/rtl

# restore original sysutils.inc
rm ../objpas/sysutils/sysutils.inc
mv ../objpas/sysutils/oldsysutils.inc ../objpas/sysutils/sysutils.inc

# remove units dir in fpcsrc
echo Remove units directory in fpcsrc
rmdir ../units/arm-embedded
rmdir ../units


